### ISSUE TITLE
題庫功能 - 引用題庫程式碼 

### ISSUE THREAD

**Issue by Yojijun** [we-have-TTA/iCoder#121]
@RexKao

**Comment by RexXKao** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [題庫功能 - 引用題庫程式碼](https://trello.com/c/XNCQOwgP/34-%E9%A1%8C%E5%BA%AB%E5%8A%9F%E8%83%BD-%E5%BC%95%E7%94%A8%E9%A1%8C%E5%BA%AB%E7%A8%8B%E5%BC%8F%E7%A2%BC)

**Comment by noracami** [comment]
👍
