### ISSUE TITLE
Action Cable - 程式碼同步執行，畫面同步

### ISSUE THREAD

**Issue by chutienyuan** [we-have-TTA/iCoder#124]

**Comment by Yojijun** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [優化畫板-新增橡皮擦](https://trello.com/c/Gx1ww19d/37-%E5%84%AA%E5%8C%96%E7%95%AB%E6%9D%BF-%E6%96%B0%E5%A2%9E%E6%A9%A1%E7%9A%AE%E6%93%A6)

**Comment by noracami** [comment]
closed by #177 .
