### ISSUE TITLE
首頁畫面美化

### ISSUE THREAD

**Issue by noracami** [we-have-TTA/iCoder#14]
首頁目前有這些元素

看看有缺或是覺得之後不會用到都可以討論

明天（８/２２）過後就照下面列點切出給大家實做

- [x] #19
  - logo
  - 下方各站點連結
  - 登入
  - 註冊
- [x] #20
  - 聯絡資訊
    - 社群連結
    - 需要協助？
    - 伺服器狀態
  - 下方各站點連結
- [x] #21
- [ ] flow chart 流程
- [ ] slim banner
- [x] #22
- [x] #23
- [ ] testimonial 案例見證
- [ ] stat bubble 使用量
- [x] #24

**Comment by noracami** [comment]
close #3 .

**Comment by Yojijun** [comment]
請問請問其中的
案例見證 ->是指我們完成後的各種使用案例嗎
然後這兩個 “伺服器狀態”  “使用量” 目前偏模糊，我需要被翻譯>_<

**Comment by noracami** [comment]
照搬官網的

> 案例見證：別人用過說讚

> 伺服器狀態：看這個頁面最下面 `Status` 那個連結

> 使用量：呈現多少人、多少單位、多少場次（舉例）使用這個服務，資料視覺化的概念
