### ISSUE TITLE
修正room列表點選只顯示自己開的room後 css 不一致

### ISSUE THREAD

**Issue by RexXKao** [we-have-TTA/iCoder#149]
<img width="1289" alt="截圖 2022-09-14 下午4 04 26" src="https://user-images.githubusercontent.com/110017175/190097210-98dd47dc-9249-434e-b886-5586abb276b4.png">
<img width="1289" alt="截圖 2022-09-14 下午4 04 30" src="https://user-images.githubusercontent.com/110017175/190097226-7b21ca09-3706-4c24-8f88-e87661deced5.png">

**Comment by noracami** [comment]
closed by #184
