### ISSUE TITLE
會議室ＣＲＵＤ

### ISSUE THREAD

**Issue by chutienyuan** [we-have-TTA/iCoder#16]
- [ ] CRUD
- [ ] UI Design

**Comment by chutienyuan** [comment]
![image](https://user-images.githubusercontent.com/37494873/186097689-0b88b022-ccfb-4ce6-b9b7-4f084cabdd2e.png)

**Comment by noracami** [comment]
@chutienyuan @oSeanChen 
你現在正在做的會議室
Model 取名叫什麼？

**Comment by chutienyuan** [comment]
> @chutienyuan @oSeanChen 你現在正在做的會議室 Model 取名叫什麼？

room

**Comment by noracami** [comment]
那 ＬＡＢＥＬ 改叫 Room 囉?
@oSeanChen
