### ISSUE TITLE
確認目標

### ISSUE THREAD

**Issue by noracami** [we-have-TTA/iCoder#33]
> @oSeanChen — 8/26 20:55
> 這週需要先可以讓整條路線出來 ，註冊 創立會議 進入會議頁面

![goal20220827](https://cdn.discordapp.com/attachments/808663045109710898/1012764834569396276/unknown.png)
[excalidraw.com](https://excalidraw.com/#json=jgjkr6CAOghutmHDUnIMY,e9SqasVfYkPNGPoAYLf7vQ)
# 頁面幫大家標好了，覺得應該完成到哪項？
（到８／２８ １７：００）

**Comment by oSeanChen** [comment]
### 8/21-8/27 完成事項

> 完成會員登入註冊系統基本功能
#### devise 套件建立

#### 註冊及登入 
- 一般註冊及登入
- 註冊時填寫email username password confirm_password
- 第三方google註冊及登入

#### 介面及排版
- i18n中文化界面、錯誤訊息等
- 基本各頁面tailwing排版

#### 忘記密碼
- 寄出更改指引信件
- 可以更改密碼

**Comment by Yojijun** [comment]
### 本階段完成
 **Canvas**
未來需調整游標差距

**Comment by RexXKao** [comment]
-  目前可藉由畫面點擊切換並啟用不同語言container
- webssh、不同語言image已上傳待其他組員於各自本機測試
- 待rooms model分支併入後再將功能串起來測試
- 尚在努力將專案用docker打包起來
