### ISSUE TITLE
Questions ->資料排序整理 以及題號呈現模式處理

### ISSUE THREAD

**Issue by Yojijun** [we-have-TTA/iCoder#83]
1.目前新增題目 ，最新的都會在最下面，考慮把逆向處理，新的在最上面
2.刪除後  題目編號修正
![image](https://user-images.githubusercontent.com/108692004/188508695-75219543-76bf-4e4b-9a3f-2f3d87ddbddd.png)

**Comment by Yojijun** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [題庫-最新在最上面](https://trello.com/c/CVc6jJSM/39-%E9%A1%8C%E5%BA%AB-%E6%9C%80%E6%96%B0%E5%9C%A8%E6%9C%80%E4%B8%8A%E9%9D%A2)

**Comment by noracami** [comment]
close until pull request close
